import './globals.css'
import { Inter } from 'next/font/google'
import Navigator from '@/components/navigator'
import { cn } from '@/components/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css"/>
      </head>
      <body
        data-theme="dark"
        className={
        cn(
          inter.className,
          // 'min-h-screen'
        )
      }>
        <Navigator />
        {children}
      </body>
    </html>
  )
}
