export const memberData = [
	{ login: 'rdv', name: 'Rod Van Meter' },
	{ login: 'michal', name: 'Michal Hajdušek' },
	{ login: 'shota', name: 'Shota Nagayama' },
	{ login: 'bernard', name: 'Bernard Ousmane Sane' },
	{ login: 'amin', name: 'Amin Taherkhani' },
	{ login: 'shigeya', name: 'Shigeya Suzuki' },
	{ login: 'sara', name: 'Sara A. Metwalli' },
	{ login: 'whit3z', name: 'Naphan Benchasattabuse' },
	{ login: 'poramet', name: 'Poramet Pathumsoot' },
	{ login: 'banknatchapol', name: 'Natchapol (Bank) Patamawisut' },
	{ login: 'sam', name: 'Samanvay Sharma' },
	{ login: 'dave', name: 'Makoto Nakai' },
	{ login: 'syu', name: 'Yinjie Zhou' },
	{ login: 'austinh', name: 'Austin Huang' },
	{ login: 'pawan', name: 'Pawan Sharma Poudel' },
	{ login: 'michael', name: 'Michael Peyron' },
	{ login: 'voy', name: 'Hikaru Yokomori' },
	{ login: 'ken-tea', name: 'YUMOTO Kento' },
	{ login: 'collodi', name: 'Hyensoo Choi' },
	{ login: 'morishita', name: 'Wataru Morishita' },
	{ login: 'bob', name: 'Monet Tokuyama' },
	{ login: 'soon', name: 'Kento Samuel Soon' },
	{ login: 'mia', name: 'Marii Koyama' },
	{ login: 'aman', name: 'Aman Y. Tekleab' },
	{ login: 'driedbones05', name: 'Hien Nguyen' },
	{ login: 'riya', name: 'Shreya Kafle' },
	{ login: 'junseo', name: 'Junseo Kwak' },
	{ login: 'mono', name: 'Tetsuma Ariyoshi' },
	{ login: 'tsukue', name: 'Mikawa-Mallery Takumi' },
	{ login: 'l0gic', name: 'Haruka Sakate' },
	{ login: 'tomshen', name: 'Yifeng (Tom) Shen' },
	{ login: 'pura', name: 'Akash prasad' },
	{ login: 'joo', name: 'Xu Haoran' },
	{ login: 'atodd', name: 'Andrew Todd' },
	{ login: 'rikachan', name: 'Kanazawa Yoshiki' },
	{ login: 'larz', name: 'Lars Matsumiya' },
	{ login: 'k0uki', name: 'Kouki Maeda' },
	{ login: 'manasvi', name: 'Manasvi(Mana) Patwardhan' },
	{ login: 'kyuryu', name: 'Yuki Kurosawa' },
	{ login: 'siddartha', name: 'Siddartha(Sid) Bhandari' },
	{ login: 'kenya', name: 'Kenya Suzuki' },
	{ login: 'remon', name: 'Daisuke Takeuchi' },
	{ login: 'sakumatcho', name: 'Daisuke Sakuma' },
	{ login: 'takafumi', name: 'Takafumi Oka' },
	{ login: 'syui', name: 'Gordon Cui' },
	{ login: 'yuta0709', name: 'Yuta Imahoko' },
	// Alumni
	{ login: 'parton', name: 'Shin Nishio' },
	{ login: 'satoh', name: 'Takahiko Satoh' },
	{ login: 'zigen', name: 'Kentaro Teramoto' },
	{ login: 'shingy', name: 'Shigetora Miyashita' },
]

// Order configuration - this controls the rendering order
export const memberOrder = memberData.map((member) => member.login)
